# [[hankeltimescans]]
# pointPath = "../punktar/monotile150couplings.h5"
# outfile = "../gögn/monotile150scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 1, end = 24, n = 400 }
# t = { start = 0, end = 100, n = 10 }

# [[hankeltimescans]]
# pointPath = "../punktar/monotile259couplings.h5"
# outfile = "../gögn/monotile259scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 1, end = 24, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
[[hankeltimescans]]
pointPath = "../punktar/monotile404couplings.h5"
outfile = "../gögn/monotile404scaletimescan.h5"
ps = { start = 0.2, end = 1.0, n = 1 }
alphas = { start = 1, end = 1, n = 1 }
js = { start = 1, end = 1, n = 1 }
rscales = { start = 1, end = 24, n = 400 }
t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/square100couplings.h5"
# outfile = "../gögn/square100scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/square225couplings.h5"
# outfile = "../gögn/square225scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/square400couplings.h5"
# outfile = "../gögn/square400scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/tetrille183couplings.h5"
# outfile = "../gögn/tetrille183scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/tetrille303couplings.h5"
# outfile = "../gögn/tetrille303scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/tetrille462couplings.h5"
# outfile = "../gögn/tetrille462scaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/tetrille201dcouplings.h5"
# outfile = "../gögn/tetrille201dscaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/tetrille305dcouplings.h5"
# outfile = "../gögn/tetrille305dscaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 4, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }
#
# [[hankeltimescans]]
# pointPath = "../punktar/tetrille462dcouplings.h5"
# outfile = "../gögn/tetrille462dscaletimescan.h5"
# ps = { start = 0.2, end = 1.0, n = 1 }
# alphas = { start = 1, end = 1, n = 1 }
# js = { start = 1, end = 1, n = 1 }
# rscales = { start = 0.1, end = 16, n = 400 }
# t = { start = 0, end = 100, n = 10000 }

# [basicdistance]
# outfile = "distancescanloweralpha.h5"
# alpha = 8
# p = 1
# j = 10
# sep = { start = 5, end = 40, n = 1000 }
# t = { start = 0, end = 480, n = 11024 }

# [tetm]
# outfile = "threepointrun.h5"
# pointPath = "threepoints.h5"
# p = -0.1
# alpha = 1
# j = 1
# rscale = 8
# t = { start = 0, end = 100, n = 10000 }
