[PreConf]
sharpening = 1000.0
cutoff = 0.1
searchRadius = 1.01
pointPath = "../data/hexgrid.txt"
H5Filename = "esection.h5"
doEsection = true
doFullSDF = false
saveHamiltonian = false
saveDiagonalisation = true
fixed_e = -1

[DispKline]
start = [0.0, 0.0]
end = [1.0, 0.0]
n = 2000

[DispE]
n = 2000

[SDFKx]
start = -1.0
end = 1.0
n = 2000

[SDFKy]
start = -1.0
end = 1.0
n = 2000

[SDFE]
n = 200
