pointPath = "../punktar/monotile404couplings.h5"
outfile = "../gögn/square400scaletimescanr3.3.h5"
p = 0.2
alpha = 1
j = 1
rscale = 3.5
dt = 0.01

# pointPath = "../punktar/monotile404couplings.h5"
# outfile = "../gögn/monotile404scaletimescanr3.5.h5"
# p = 0.2
# alpha = 1
# j = 1
# rscale = 3.5
# dt = 0.01

